name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: |
          mkdir -p dist/maxoform-linux-amd64

          CGO_ENABLED=0 \
          GOOS=linux \
          GOARCH=amd64 \
          go build \
            -ldflags="-s -w" \
            -o dist/maxoform-linux-amd64/maxoform \
            ./cmd

      - name: Copy data directory
        run: |
          cp -r data dist/maxoform-linux-amd64/

      - name: Create tarball
        run: |
          cd dist
          tar -czf maxoform-linux-amd64.tar.gz maxoform-linux-amd64

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            ## How to install and run

            ```bash
            wget https://github.com/maxogod/maxoform/releases/download/${{ github.ref_name }}/maxoform-linux-amd64.tar.gz
            tar xzf maxoform-linux-amd64.tar.gz
            cd maxoform-linux-amd64
            MF_SSH_PASSPHRASE=mypassphrase ./maxoform --config data/configuration/packages.yaml --settings-dir data/settings --dconf-manifest data/settings/manifest.yaml
            ```
          files: |
            dist/maxoform-linux-amd64.tar.gz
